In [1]:
import csv
fifa_file = open('Fifa19.csv', encoding='utf-8')
file_reader = csv.reader(fifa_file)
player_data = list(file_reader)
fifa_file.close()
header = player_data[0]
player_data = player_data[1:]
for row in player_data:
    for idx in [2,4]:
        row[idx] = float(row[idx])

In [2]:
def cell(row_idx, col_name):
    col_idx = header.index(col_name)
    val = player_data[row_idx][col_idx]
    return val

In [3]:
def transition(value):
    if value[-1].lower() == "m":
        stripped = value[1:-1]
        stripped_float = float(stripped)
        millions = stripped_float * 1000000
        return millions
    if value[-1].lower() == "k":
        k_stripped = value[1:-1]
        k_stripped_float = float(k_stripped)
        k_thousands = k_stripped_float * 100000
        return k_thousands
    if value[-1].isdigit():
        digit_stripped = value[1:]
        digit_stripped_float = float(digit_stripped)
        return digit_stripped_float
    else: 
        pass

In [4]:
def get_column(col_name):
    new_list = []
    for i in range(len(player_data)):
        if col_name == 7:
            [s[1:-1] for s in player_data]
        column = player_data[i][col_name]
        new_list.append(column)
    return new_list

In [ ]:
def oldest_player(idx):
    oldest_age = 0 
    name_oldest = 0

In [5]:
#q1
def get_player_name(idx):
    oldest_age = 0
    name_oldest_age = 0
    for i in range(len(player_data)):
        row = player_data[i]
        age = row[idx]
        
        if age > oldest_age:
            oldest_age = age
            max_idx = i
            name_oldest_age = player_data[max_idx][1]
    return name_oldest_age
get_player_name(2)

'O. Pérez'

In [6]:
#q2
def get_highest_paid(idx):
    highest_paid = 0
    name_of_highest_val = " "
    for i in range(len(player_data)):
        row = player_data[i]
        val = transition(row[7])
        if val > highest_paid:
            highest_paid = val
            max_idx = i
            name_of_highest_val = player_data[max_idx][idx]
    return name_of_highest_val
get_highest_paid(1)

'L. Messi'

In [7]:
#q3 
def get_highest_val(col_idx):
    highest_val = 0
    for i in range(len(player_data)):
        row = player_data[i]
        val = transition(row[6])
        if val > highest_val:
            highest_val = val
            max_idx = i
            name_of_highest_val = player_data[max_idx][col_idx]
    return name_of_highest_val
get_highest_val(1)

'Neymar Jr'

In [8]:
#q4
def player_to_dict(name):
    for row in player_data:
        if row[1] == name:
            player_vals = row
            player_keys = header
            dic = {}
            for i in range(len(player_keys)):
                dic[player_keys[i]] = player_vals[i]
    return dic

def player_club(name):
    x = player_to_dict(name)
    return x.get("Club")

player_club(get_highest_val(1))
player_club("Neymar Jr")

'Paris Saint-Germain'

In [9]:
#q5
get_column(3)[0:5]

['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium']

In [10]:
#q6
names = get_column(1)
names.sort()
s = names[0:5]
s

['A. Abang', 'A. Abdellaoui', 'A. Abdennour', 'A. Abdi', 'A. Abdu Jaber']

In [11]:
#q7
def fifa_avg(col_name):
    count = 0
    total = 0
    average = 0 
    net = get_column(col_name)
    for i in range(len(player_data)):
        total += net[i]
        count += 1 
    average = total / count 
    return average

In [12]:
#q8
def fifa_avg(col_name):
    count = 0
    total = 0
    average = 0 
    net = get_column(col_name)
    for i in range(len(player_data)):
        total += net[i]
        count += 1 
    average = total / count 
    return average 
fifa_avg(2)

25.122205745043114

In [13]:
#q9
def player_count(country):
    count = 0
    cols = get_column(3)
    for i in range(len(player_data)):
        if cols[i] == country:
            count += 1
    return(count)
        
      
player_count("Portugal")

322

In [14]:
#q10
player_count("Brazil")

827

In [15]:
#q11

highest_country_count = 0
highest = 0
country_id = 0
column = set(get_column(3))
for i in column:
    if player_count(i) > highest:
        highest = player_count(i)
        country_idx = i
country_idx

'England'

In [16]:
#q12
def player_to_dict(player_id):
    for row in player_data:
        if int(row[0]) == player_id:
            player_vals = row
            player_keys = header
            dic = {}

            for i in range(len(player_keys)):
                dic[player_keys[i]] = player_vals[i]
    return dic
player_to_dict(20801)

{'Id': '20801',
 'Name': 'Cristiano Ronaldo',
 'Age': 33.0,
 'Nationality': 'Portugal',
 'Overall': 94.0,
 'Club': 'Juventus',
 'Value': '€77M',
 'Wage': '€405K',
 'Preferred Foot': 'Right',
 'Jersey Number': '7',
 'Height': "6'2",
 'Weight': '183lbs'}

In [17]:
#q13
player_to_dict(190871)

{'Id': '190871',
 'Name': 'Neymar Jr',
 'Age': 26.0,
 'Nationality': 'Brazil',
 'Overall': 92.0,
 'Club': 'Paris Saint-Germain',
 'Value': '€118.5M',
 'Wage': '€290K',
 'Preferred Foot': 'Right',
 'Jersey Number': '10',
 'Height': "5'9",
 'Weight': '150lbs'}

In [18]:
#q14
player_to_dict(158023)

{'Id': '158023',
 'Name': 'L. Messi',
 'Age': 31.0,
 'Nationality': 'Argentina',
 'Overall': 94.0,
 'Club': 'FC Barcelona',
 'Value': '€110.5M',
 'Wage': '€565K',
 'Preferred Foot': 'Left',
 'Jersey Number': '10',
 'Height': "5'7",
 'Weight': '159lbs'}

In [19]:
#q15
player_to_dict(192985)

{'Id': '192985',
 'Name': 'K. De Bruyne',
 'Age': 27.0,
 'Nationality': 'Belgium',
 'Overall': 91.0,
 'Club': 'Manchester City',
 'Value': '€102M',
 'Wage': '€355K',
 'Preferred Foot': 'Right',
 'Jersey Number': '7',
 'Height': "5'11",
 'Weight': '154lbs'}

In [20]:
#q16
def amount_of_players(column_idx):
    keys = list(set(get_column(column_idx)))
    dic = {}
    for i in keys:
        dic[i] = player_count(i)
    return dic
amount_of_players(3)

{'Nicaragua': 2,
 'Ivory Coast': 100,
 'Colombia': 618,
 'Argentina': 937,
 'Liechtenstein': 3,
 'Trinidad & Tobago': 4,
 'Ethiopia': 1,
 'Russia': 79,
 'Guinea Bissau': 15,
 'Paraguay': 85,
 'Faroe Islands': 6,
 'India': 30,
 'Cuba': 4,
 'Mozambique': 4,
 'Angola': 15,
 'Korea DPR': 4,
 'Latvia': 6,
 'Dominican Republic': 2,
 'Comoros': 6,
 'Costa Rica': 30,
 'New Zealand': 44,
 'Belize': 1,
 'Netherlands': 453,
 'Liberia': 1,
 'Haiti': 10,
 'Uruguay': 149,
 'New Caledonia': 1,
 'Luxembourg': 8,
 'Moldova': 5,
 'Azerbaijan': 5,
 'Madagascar': 12,
 'Portugal': 322,
 'Iceland': 47,
 'South Africa': 71,
 'Sweden': 397,
 'El Salvador': 5,
 'Tanzania': 3,
 'São Tomé & Príncipe': 1,
 'Spain': 1072,
 'Ukraine': 73,
 'FYR Macedonia': 20,
 'Estonia': 13,
 'Germany': 1198,
 'Northern Ireland': 80,
 'Mexico': 366,
 'Slovenia': 55,
 'France': 914,
 'St Lucia': 1,
 'Saudi Arabia': 340,
 'England': 1662,
 'Wales': 129,
 'Serbia': 126,
 'Rwanda': 1,
 'Slovakia': 54,
 'China PR': 392,
 'Guam': 1,
 'Botswana': 1,
 'Togo': 12,
 'Guinea': 31,
 'Burkina Faso': 16,
 'Croatia': 126,
 'Panama': 15,
 'Senegal': 130,
 'St Kitts Nevis': 3,
 'Korea Republic': 335,
 'Namibia': 3,
 'Fiji': 1,
 'Kuwait': 1,
 'Georgia': 26,
 'Bolivia': 30,
 'Austria': 298,
 'Sierra Leone': 6,
 'Zambia': 9,
 'Puerto Rico': 1,
 'Zimbabwe': 13,
 'Venezuela': 67,
 'Armenia': 10,
 'Jamaica': 32,
 'Lithuania': 8,
 'Suriname': 4,
 'Iraq': 7,
 'Palestine': 1,
 'Barbados': 3,
 'Kazakhstan': 4,
 'Hungary': 38,
 'Brazil': 827,
 'Mali': 43,
 'Chile': 391,
 'Albania': 40,
 'Iran': 17,
 'Afghanistan': 4,
 'Thailand': 5,
 'Ecuador': 43,
 'Tunisia': 32,
 'Denmark': 336,
 'Switzerland': 220,
 'Czech Republic': 100,
 'Japan': 478,
 'Republic of Ireland': 368,
 'Lebanon': 1,
 'Guyana': 3,
 'Nigeria': 121,
 'Oman': 1,
 'United States': 353,
 'Cyprus': 8,
 'United Arab Emirates': 1,
 'Benin': 15,
 'Bosnia Herzegovina': 61,
 'Uganda': 6,
 'Grenada': 1,
 'Eritrea': 2,
 'Curacao': 14,
 'Bermuda': 2,
 'Honduras': 16,
 'Antigua & Barbuda': 4,
 'Kenya': 10,
 'Qatar': 1,
 'Belgium': 260,
 'Algeria': 60,
 'Canada': 64,
 'Australia': 236,
 'Italy': 702,
 'Peru': 37,
 'Equatorial Guinea': 5,
 'Mauritius': 1,
 'Egypt': 31,
 'Congo': 25,
 'Niger': 3,
 'Indonesia': 1,
 'Mauritania': 4,
 'Morocco': 85,
 'Libya': 4,
 'South Sudan': 1,
 'Norway': 341,
 'Jordan': 1,
 'Kosovo': 33,
 'Montserrat': 4,
 'Guatemala': 3,
 'Poland': 350,
 'Finland': 67,
 'Malta': 1,
 'Cape Verde': 19,
 'Gabon': 15,
 'Central African Rep.': 3,
 'DR Congo': 52,
 'Belarus': 4,
 'Hong Kong': 2,
 'Philippines': 2,
 'Andorra': 1,
 'Chad': 2,
 'Israel': 14,
 'Gambia': 15,
 'Syria': 9,
 'Sudan': 3,
 'Greece': 102,
 'Burundi': 3,
 'Romania': 54,
 'Montenegro': 23,
 'Ghana': 114,
 'Uzbekistan': 2,
 'Bulgaria': 32,
 'Turkey': 303,
 'Cameroon': 90,
 'Scotland': 286}

In [21]:
def jersey():
    count = 0 
    cols = get_column(9)
    return cols
jersey()

['10',
 '7',
 '10',
 '1',
 '7',
 '10',
 '10',
 '9',
 '15',
 '1',
 '9',
 '8',
 '10',
 '21',
 '13',
 '21',
 '9',
 '7',
 '22',
 '1',
 '5',
 '21',
 '1',
 '10',
 '3',
 '10',
 '10',
 '14',
 '10',
 '10',
 '22',
 '10',
 '7',
 '14',
 '5',
 '12',
 '11',
 '1',
 '9',
 '2',
 '1',
 '1',
 '23',
 '9',
 '26',
 '6',
 '1',
 '9',
 '17',
 '18',
 '14',
 '5',
 '17',
 '4',
 '3',
 '19',
 '11',
 '31',
 '10',
 '4',
 '10',
 '9',
 '4',
 '6',
 '12',
 '11',
 '13',
 '19',
 '11',
 '14',
 '19',
 '2',
 '5',
 '4',
 '10',
 '25',
 '8',
 '37',
 '21',
 '10',
 '18',
 '13',
 '18',
 '6',
 '26',
 '8',
 '8',
 '9',
 '4',
 '30',
 '10',
 '9',
 '1',
 '7',
 '8',
 '17',
 '8',
 '44',
 '9',
 '6',
 '19',
 '14',
 '29',
 '14',
 '23',
 '9',
 '3',
 '4',
 '3',
 '9',
 '23',
 '24',
 '13',
 '14',
 '8',
 '15',
 '11',
 '20',
 '3',
 '5',
 '14',
 '8',
 '20',
 '2',
 '10',
 '7',
 '1',
 '14',
 '22',
 '11',
 '17',
 '12',
 '31',
 '1',
 '4',
 '2',
 '21',
 '7',
 '11',
 '17',
 '22',
 '1',
 '10',
 '6',
 '18',
 '10',
 '19',
 '16',
 '9',
 '1',
 '33',
 '10',
 '15',
 '7',
 '10',
 '11',
 '33',
 '7',
 '4',
 '9',
 '3',
 '8',
 '24',
 '8',
 '29',
 '20',
 '24',
 '9',
 '25',
 '14',
 '9',
 '22',
 '17',
 '10',
 '7',
 '28',
 '17',
 '13',
 '14',
 '6',
 '1',
 '15',
 '5',
 '11',
 '7',
 '8',
 '27',
 '22',
 '12',
 '1',
 '5',
 '13',
 '20',
 '9',
 '21',
 '44',
 '13',
 '1',
 '17',
 '7',
 '3',
 '1',
 '15',
 '16',
 '28',
 '8',
 '9',
 '19',
 '77',
 '30',
 '1',
 '8',
 '1',
 '1',
 '1',
 '8',
 '8',
 '6',
 '16',
 '4',
 '19',
 '7',
 '1',
 '16',
 '25',
 '1',
 '3',
 '16',
 '8',
 '22',
 '13',
 '3',
 '1',
 '18',
 '17',
 '14',
 '14',
 '23',
 '21',
 '15',
 '27',
 '3',
 '16',
 '20',
 '10',
 '15',
 '7',
 '2',
 '13',
 '5',
 '17',
 '9',
 '9',
 '10',
 '7',
 '22',
 '7',
 '16',
 '16',
 '6',
 '15',
 '26',
 '6',
 '12',
 '5',
 '7',
 '1',
 '9',
 '17',
 '17',
 '11',
 '10',
 '23',
 '5',
 '4',
 '12',
 '6',
 '6',
 '8',
 '13',
 '10',
 '20',
 '27',
 '11',
 '5',
 '21',
 '7',
 '15',
 '11',
 '10',
 '12',
 '11',
 '10',
 '21',
 '7',
 '9',
 '8',
 '10',
 '16',
 '5',
 '23',
 '14',
 '8',
 '20',
 '9',
 '15',
 '18',
 '24',
 '33',
 '1',
 '1',
 '6',
 '47',
 '21',
 '13',
 '7',
 '20',
 '1',
 '1',
 '11',
 '8',
 '9',
 '5',
 '7',
 '2',
 '8',
 '8',
 '2',
 '21',
 '22',
 '11',
 '24',
 '16',
 '77',
 '9',
 '11',
 '6',
 '10',
 '1',
 '23',
 '20',
 '14',
 '3',
 '13',
 '16',
 '17',
 '7',
 '14',
 '4',
 '5',
 '7',
 '9',
 '22',
 '6',
 '2',
 '16',
 '38',
 '11',
 '31',
 '40',
 '7',
 '31',
 '9',
 '23',
 '10',
 '10',
 '20',
 '9',
 '6',
 '17',
 '23',
 '17',
 '23',
 '22',
 '21',
 '18',
 '92',
 '12',
 '10',
 '23',
 '10',
 '11',
 '13',
 '36',
 '8',
 '1',
 '5',
 '4',
 '5',
 '28',
 '21',
 '27',
 '26',
 '87',
 '18',
 '22',
 '3',
 '10',
 '5',
 '16',
 '22',
 '28',
 '20',
 '27',
 '18',
 '4',
 '16',
 '11',
 '17',
 '7',
 '22',
 '17',
 '18',
 '29',
 '17',
 '8',
 '8',
 '19',
 '10',
 '5',
 '6',
 '10',
 '4',
 '11',
 '2',
 '25',
 '1',
 '20',
 '9',
 '5',
 '7',
 '34',
 '33',
 '15',
 '14',
 '19',
 '27',
 '11',
 '23',
 '1',
 '7',
 '22',
 '10',
 '3',
 '8',
 '3',
 '8',
 '1',
 '23',
 '10',
 '4',
 '4',
 '5',
 '6',
 '23',
 '4',
 '9',
 '20',
 '8',
 '9',
 '21',
 '7',
 '1',
 '23',
 '2',
 '2',
 '13',
 '3',
 '5',
 '7',
 '4',
 '22',
 '25',
 '31',
 '16',
 '12',
 '7',
 '11',
 '24',
 '14',
 '9',
 '21',
 '17',
 '32',
 '44',
 '9',
 '20',
 '2',
 '34',
 '10',
 '13',
 '7',
 '2',
 '3',
 '5',
 '13',
 '22',
 '6',
 '14',
 '19',
 '31',
 '10',
 '14',
 '13',
 '31',
 '12',
 '18',
 '10',
 '4',
 '26',
 '22',
 '11',
 '1',
 '21',
 '18',
 '20',
 '6',
 '2',
 '10',
 '3',
 '18',
 '7',
 '8',
 '9',
 '10',
 '10',
 '1',
 '4',
 '8',
 '15',
 '22',
 '16',
 '37',
 '26',
 '24',
 '19',
 '24',
 '31',
 '4',
 '10',
 '27',
 '1',
 '27',
 '20',
 '13',
 '19',
 '16',
 '14',
 '83',
 '33',
 '31',
 '13',
 '9',
 '9',
 '70',
 '15',
 '6',
 '7',
 '21',
 '25',
 '30',
 '18',
 '14',
 '11',
 '12',
 '14',
 '15',
 '2',
 '12',
 '23',
 '10',
 '1',
 '29',
 '18',
 '21',
 '22',
 '4',
 '17',
 '25',
 '7',
 '7',
 '6',
 '11',
 '33',
 '3',
 '4',
 '11',
 '16',
 '20',
 '7',
 '21',
 '13',
 '9',
 '23',
 '25',
 '8',
 '21',
 '8',
 '7',
 '18',
 '10',
 '19',
 '25',
 '23',
 '15',
 '3',
 '31',
 '19',
 '9',
 '25',
 '4',
 '8',
 '4',
 '6',
 '6',
 '19',
 '4',
 '22',
 '7',
 '6',
 '1',
 '9',
 '30',
 '13',
 '13',
 '10',
 '15',
 '31',
 '6',
 '16',
 '17',
 '20',
 '11',
 '15',
 '12',
 '23',
 '19',
 '11',
 '19',
 '18',
 '24',
 '26',
 '8',
 '11',
 '11',
 '3',
 '15',
 '1',
 '7',
 '17',
 '23',
 '27',
 '18',
 '13',
 '4',
 '10',
 '10',
 '20',
 '11',
 '9',
 '18',
 '17',
 '9',
 '11',
 '7',
 '2',
 '35',
 '18',
 '6',
 '4',
 '21',
 '19',
 '21',
 '6',
 '17',
 '10',
 '10',
 '2',
 '6',
 '18',
 '1',
 '6',
 '9',
 '2',
 '89',
 '23',
 '25',
 '16',
 '2',
 '18',
 '27',
 '5',
 '12',
 '10',
 '9',
 '17',
 '31',
 '13',
 '9',
 '18',
 '8',
 '19',
 '1',
 '12',
 '27',
 '17',
 '21',
 '5',
 '11',
 '19',
 '1',
 '18',
 '19',
 '22',
 '8',
 '10',
 '11',
 '18',
 '20',
 '15',
 '10',
 '17',
 '1',
 '2',
 '10',
 '5',
 '16',
 '3',
 '14',
 '29',
 '5',
 '10',
 '8',
 '15',
 '1',
 '14',
 '20',
 '17',
 '16',
 '18',
 '5',
 '8',
 '19',
 '17',
 '2',
 '22',
 '7',
 '29',
 '56',
 '1',
 '10',
 '35',
 '21',
 '18',
 '3',
 '16',
 '18',
 '24',
 '99',
 '77',
 '13',
 '28',
 '9',
 '9',
 '18',
 '6',
 '7',
 '13',
 '12',
 '3',
 '2',
 '19',
 '8',
 '15',
 '14',
 '17',
 '87',
 '2',
 '21',
 '57',
 '5',
 '19',
 '91',
 '11',
 '24',
 '24',
 '16',
 '3',
 '57',
 '17',
 '17',
 '10',
 '5',
 '18',
 '20',
 '47',
 '23',
 '31',
 '5',
 '8',
 '11',
 '23',
 '8',
 '1',
 '10',
 '6',
 '2',
 '15',
 '23',
 '4',
 '1',
 '10',
 '20',
 '14',
 '27',
 '2',
 '11',
 '21',
 '30',
 '12',
 '29',
 '24',
 '10',
 '9',
 '9',
 '18',
 '4',
 '30',
 '24',
 '25',
 '6',
 '5',
 '19',
 '3',
 '92',
 '11',
 '19',
 '5',
 '5',
 '26',
 '22',
 '23',
 '5',
 '19',
 '17',
 '3',
 '14',
 '27',
 '6',
 '1',
 '20',
 '10',
 '7',
 '8',
 '32',
 '9',
 '15',
 '26',
 '15',
 '16',
 '23',
 '14',
 '17',
 '1',
 '4',
 '86',
 '27',
 '11',
 '10',
 '7',
 '2',
 '1',
 '10',
 '4',
 '22',
 '25',
 '3',
 '1',
 '22',
 '6',
 '4',
 '5',
 '20',
 '10',
 '8',
 '26',
 '25',
 '17',
 '3',
 '3',
 '10',
 '15',
 '19',
 '7',
 '16',
 '9',
 '38',
 '16',
 '8',
 '3',
 '19',
 '5',
 '14',
 '30',
 '8',
 '4',
 '17',
 '20',
 '5',
 '28',
 '99',
 '9',
 '11',
 '22',
 '8',
 '19',
 '5',
 '8',
 '5',
 '8',
 '1',
 '18',
 '22',
 '20',
 '10',
 '20',
 '1',
 '11',
 '7',
 '18',
 '20',
 '18',
 '18',
 '21',
 '2',
 '4',
 '7',
 '1',
 '16',
 '8',
 '19',
 '9',
 '11',
 '6',
 '13',
 '3',
 '21',
 '5',
 '9',
 '4',
 '10',
 '10',
 '9',
 '4',
 '30',
 '29',
 '1',
 '7',
 '22',
 '17',
 '16',
 '13',
 '9',
 '16',
 '12',
 '20',
 '27',
 '5',
 '19',
 '19',
 '23',
 '4',
 '22',
 '9',
 '14',
 '6',
 '27',
 '1',
 '16',
 '17',
 '17',
 '17',
 '8',
 '19',
 '22',
 '15',
 '15',
 '3',
 '16',
 '8',
 '2',
 '6',
 '9',
 '5',
 '99',
 '14',
 '6',
 '7',
 '14',
 '22',
 ...]

In [22]:
#q17
numbers = jersey()
def players_to_jersey(numbers):
    jersey_dict = {}
    for i in numbers:
        if i in jersey_dict:
            jersey_dict[i] += 1 
        else:
            jersey_dict[i] = 1
    return jersey_dict
    
players_to_jersey(numbers)

{'10': 593,
 '7': 604,
 '1': 566,
 '9': 577,
 '15': 501,
 '8': 612,
 '21': 536,
 '13': 419,
 '22': 531,
 '5': 579,
 '3': 547,
 '14': 542,
 '12': 390,
 '11': 590,
 '2': 519,
 '23': 546,
 '26': 390,
 '6': 586,
 '17': 554,
 '18': 545,
 '4': 573,
 '19': 545,
 '31': 280,
 '25': 409,
 '37': 135,
 '30': 371,
 '44': 74,
 '29': 358,
 '24': 425,
 '20': 568,
 '16': 517,
 '33': 287,
 '28': 357,
 '27': 423,
 '77': 77,
 '47': 28,
 '38': 102,
 '40': 114,
 '92': 10,
 '36': 145,
 '87': 14,
 '34': 207,
 '32': 250,
 '83': 6,
 '70': 29,
 '35': 183,
 '89': 15,
 '56': 17,
 '99': 70,
 '57': 8,
 '91': 21,
 '86': 4,
 '45': 47,
 '63': 4,
 '39': 107,
 '43': 41,
 '42': 54,
 '93': 14,
 '72': 7,
 '71': 10,
 '88': 44,
 '55': 35,
 '80': 16,
 '50': 42,
 '66': 27,
 '60': 10,
 '73': 6,
 '67': 5,
 '74': 2,
 '69': 6,
 '76': 4,
 '41': 53,
 '90': 26,
 '46': 29,
 '75': 6,
 '79': 2,
 '62': 6,
 '81': 5,
 '61': 7,
 '49': 19,
 '95': 12,
 '53': 11,
 '96': 13,
 '97': 16,
 '68': 4,
 '98': 21,
 '94': 11,
 '58': 5,
 '78': 5,
 '': 60,
 '48': 17,
 '52': 10,
 '54': 11,
 '84': 4,
 '82': 5,
 '65': 4,
 '64': 2,
 '51': 7,
 '59': 5,
 '85': 1}

In [23]:
#q18
def avg_per_jersey(column_idx, variable):
    keys = list(set(get_column(column_idx)))
    new_dic = {}
    for jersey in keys:
        overall_jersey = 0
        player_overall = 0
        for row in player_data:
            if row[column_idx] == jersey:
                overall_jersey += row[variable]
                player_overall += 1
                new_dic[jersey] = overall_jersey/player_overall
    return new_dic
avg_per_jersey(9,4)

{'': 61.63333333333333,
 '71': 64.5,
 '47': 63.57142857142857,
 '44': 64.70270270270271,
 '93': 67.28571428571429,
 '73': 64.33333333333333,
 '10': 70.38617200674537,
 '54': 61.0,
 '26': 64.04358974358975,
 '45': 62.0,
 '94': 66.72727272727273,
 '57': 68.125,
 '64': 62.5,
 '52': 61.8,
 '56': 65.11764705882354,
 '91': 66.76190476190476,
 '74': 67.5,
 '27': 64.36170212765957,
 '3': 67.38939670932358,
 '1': 68.35689045936395,
 '43': 60.048780487804876,
 '11': 68.3406779661017,
 '68': 67.0,
 '53': 62.45454545454545,
 '29': 63.92178770949721,
 '88': 66.5,
 '80': 63.4375,
 '41': 61.37735849056604,
 '49': 59.68421052631579,
 '17': 66.9115523465704,
 '42': 62.5,
 '24': 64.65411764705883,
 '2': 67.58766859344894,
 '92': 68.9,
 '12': 65.43076923076923,
 '95': 65.25,
 '22': 66.31638418079096,
 '38': 61.77450980392157,
 '39': 62.52336448598131,
 '99': 64.35714285714286,
 '55': 63.0,
 '31': 63.06785714285714,
 '34': 62.072463768115945,
 '30': 63.1644204851752,
 '9': 69.28769497400347,
 '79': 71.5,
 '37': 61.785185185185185,
 '76': 68.0,
 '6': 68.19283276450511,
 '16': 66.08510638297872,
 '67': 64.6,
 '7': 68.87251655629139,
 '72': 65.0,
 '48': 61.470588235294116,
 '20': 66.7306338028169,
 '25': 64.59413202933985,
 '61': 61.57142857142857,
 '69': 68.66666666666667,
 '36': 60.5448275862069,
 '15': 66.53493013972056,
 '89': 65.4,
 '14': 66.9870848708487,
 '63': 69.0,
 '59': 57.2,
 '87': 68.35714285714286,
 '58': 62.8,
 '62': 62.0,
 '8': 68.83006535947712,
 '97': 62.4375,
 '4': 67.76614310645724,
 '96': 64.53846153846153,
 '32': 62.152,
 '65': 58.5,
 '13': 66.90214797136038,
 '28': 63.943977591036415,
 '98': 60.904761904761905,
 '85': 57.0,
 '19': 66.63669724770642,
 '84': 63.75,
 '75': 66.5,
 '33': 63.29965156794425,
 '82': 59.8,
 '51': 58.0,
 '35': 60.92896174863388,
 '81': 65.0,
 '18': 66.45688073394496,
 '66': 63.77777777777778,
 '78': 65.6,
 '90': 65.61538461538461,
 '5': 68.49740932642487,
 '46': 60.206896551724135,
 '23': 66.46886446886447,
 '83': 67.66666666666667,
 '21': 66.2723880597015,
 '70': 64.72413793103448,
 '60': 64.1,
 '50': 62.30952380952381,
 '40': 61.51754385964912,
 '86': 64.0,
 '77': 66.1038961038961}

In [24]:
#q19
davis = avg_per_jersey(9,4)

def highest_avg_overall():
    best_jersey = None
    for jersey in davis:
        if best_jersey == None or davis[jersey] > davis[best_jersey]:
            best_jersey = jersey 
    return best_jersey

highest_avg_overall()

'79'

In [25]:
#q20
def average_per(column_idx, variable):
    keys = list(set(get_column(column_idx)))
    dic = {}
    for league in keys:
        wages_league = 0
        player_count = 0
        for row in player_data:
            if row[column_idx] == league:
                wages_league += transition(row[variable])
                player_count += 1
                dic[league] = wages_league/player_count
    return dic 
        
x = average_per(5,6)
max(x)

'Śląsk Wrocław'